# Generated by Django 5.2.8 on 2025-11-13 03:11

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Organización')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='ImportacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Importación')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo Original')),
                ('registros_creados', models.PositiveIntegerField(default=0)),
                ('registros_actualizados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('DESHECHO', 'Deshecho')], default='COMPLETADO', max_length=15)),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que importó')),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'verbose_name_plural': 'Lotes de Importación',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Clase')),
                ('estudiantes', models.ManyToManyField(limit_choices_to={'groups__name': 'Estudiante'}, related_name='clases_inscritas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'groups__name': 'Profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_dirigidas', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(default=users.models.get_default_organization, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='users.organizacion')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='users/', verbose_name='Imagen de Perfil')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('telephone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Teléfono')),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal'), ('OT', 'Otro')], max_length=3, null=True, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Número de Identificación')),
                ('organizacion', models.ForeignKey(default=users.models.get_default_organization, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='users.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombres', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=70, null=True, verbose_name='Apellidos')),
                ('registrado', models.BooleanField(default=False, verbose_name='¿Ya se registró?')),
                ('rol_asignado', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Administrativo', 'Administrativo')], default='Estudiante', max_length=15, verbose_name='Rol Asignado')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistros_importados', to=settings.AUTH_USER_MODEL)),
                ('lote_importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistros', to='users.importacionlote')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregistros', to='users.organizacion')),
            ],
            options={
                'verbose_name': 'Usuario Pre-registrado',
                'verbose_name_plural': 'Usuarios Pre-registrados',
                'unique_together': {('organizacion', 'numero_identificacion')},
            },
        ),
    ]
