# Generated by Django 5.2.4 on 2025-11-06 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='importado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistros_importados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImportacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Importación')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo Original')),
                ('registros_creados', models.PositiveIntegerField(default=0)),
                ('registros_actualizados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('DESHECHO', 'Deshecho')], default='COMPLETADO', max_length=15)),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que importó')),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'verbose_name_plural': 'Lotes de Importación',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.AddField(
            model_name='preregistro',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistros', to='users.importacionlote'),
        ),
    ]
