steps:
  # Build the application (ahora incluye collectstatic)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/imago-edu', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/imago-edu']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'imago-edu'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/imago-edu'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - 'imago-edu:us-central1:imago-db'
    - '--set-env-vars'
    - 'DB_PASSWORD=NUEVO_DB_PASSWORD,DEBUG=False,GS_BUCKET_NAME=imago-media'
    - '--set-env-vars'
    - 'SECRET_KEY=NUEVA_SECRET_KEY'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/imago-edu'