# Generated by Django 5.2.4 on 2025-11-04 20:54

import django.db.models.deletion
import lecturas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2)),
                ('titulo', models.CharField(max_length=200)),
                ('grado', models.CharField(choices=[('sexto', 'Sexto'), ('septimo', 'Septimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Decimo'), ('once', 'Once')], max_length=10)),
                ('descripcion', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=lecturas.models.ruta_de_subida)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=lecturas.models.ruta_imagenes)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adjunto_comentario', models.FileField(blank=True, null=True, upload_to=lecturas.models.ruta_subida_comentario)),
                ('imagen_comentario', models.ImageField(blank=True, null=True, upload_to=lecturas.models.ruta_imagenes_comentario)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='lecturas.documento')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
