# Generated by Django 5.2.8 on 2025-11-13 04:36

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import lecturas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Autor')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Género')),
                ('slug', models.SlugField(help_text='Versión amigable para URL, se genera automáticamente.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2)),
                ('titulo', models.CharField(max_length=200)),
                ('grado', models.CharField(choices=[('sexto', 'Sexto'), ('septimo', 'Séptimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Décimo'), ('once', 'Once')], max_length=10)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=lecturas.models.ruta_de_subida)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=lecturas.models.ruta_imagenes)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nivel_dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=15, verbose_name='Nivel de Dificultad')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('autor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='lecturas.autor', verbose_name='Autor de la Obra')),
                ('generos', models.ManyToManyField(blank=True, related_name='documentos', to='lecturas.genero', verbose_name='Géneros')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adjunto_comentario', models.FileField(blank=True, null=True, upload_to=lecturas.models.ruta_subida_comentario)),
                ('imagen_comentario', models.ImageField(blank=True, null=True, upload_to=lecturas.models.ruta_imagenes_comentario)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='lecturas.comentario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='lecturas.documento')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='lecturas.documento')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
