# Generated by Django 5.2.8 on 2025-11-13 04:36

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Publicación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10, verbose_name='Estado')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación (o Programación)')),
                ('anclado', models.BooleanField(default=False, help_text='Las publicaciones ancladas aparecerán primero en la lista.', verbose_name='Anclar Publicación')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('etiquetas', taggit.managers.TaggableManager(blank=True, help_text='Una lista de etiquetas separadas por comas. Ej: Eventos, Anuncios, Verano 2024', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-anclado', '-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto Enriquecido'), ('imagen', 'Imagen'), ('embed', 'Video / Red Social'), ('cita', 'Cita Destacada')], max_length=10, verbose_name='Tipo de Bloque')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de los bloques.')),
                ('contenido_texto', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('contenido_imagen', models.ImageField(blank=True, null=True, upload_to='comunicaciones/bloques/')),
                ('tamanio_imagen', models.CharField(blank=True, choices=[('small', 'Pequeño (400px)'), ('medium', 'Mediano (600px)'), ('large', 'Grande (800px)'), ('full', 'Ancho completo')], default='medium', max_length=10, null=True)),
                ('alineacion_imagen', models.CharField(blank=True, choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10, null=True)),
                ('caption_imagen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la imagen')),
                ('contenido_embed', models.TextField(blank=True, help_text="Pega aquí el código 'embed' completo.", null=True)),
                ('contenido_cita', models.TextField(blank=True, help_text='Texto de la cita.', null=True)),
                ('autor_cita', models.CharField(blank=True, help_text='Autor de la cita (opcional).', max_length=100, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='comunicaciones.publicacion')),
            ],
            options={
                'verbose_name': 'Bloque de Contenido',
                'verbose_name_plural': 'Bloques de Contenido',
                'ordering': ['orden'],
            },
        ),
    ]
