# Generated by Django 5.2.8 on 2025-11-13 03:11

import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-anclado', '-fecha_publicacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='alineacion_imagen',
            field=models.CharField(blank=True, choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='caption_imagen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la imagen'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='tamanio_imagen',
            field=models.CharField(blank=True, choices=[('small', 'Pequeño (400px)'), ('medium', 'Mediano (600px)'), ('large', 'Grande (800px)'), ('full', 'Ancho completo')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='anclado',
            field=models.BooleanField(default=False, help_text='Las publicaciones ancladas aparecerán primero en la lista.', verbose_name='Anclar Publicación'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='etiquetas',
            field=taggit.managers.TaggableManager(blank=True, help_text='Una lista de etiquetas separadas por comas. Ej: Eventos, Anuncios, Verano 2024', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación (o Programación)'),
        ),
    ]
