# Generated by Django 5.2.8 on 2025-11-18 02:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='El texto principal y más grande del Hero.', max_length=150)),
                ('subtitulo', models.TextField(blank=True, help_text='Un texto secundario que aparece debajo del título.', max_length=300)),
                ('texto_boton', models.CharField(blank=True, max_length=50, verbose_name='Texto del Botón')),
                ('enlace_boton', models.CharField(blank=True, help_text='Ejemplo: /lecturas/', max_length=255, verbose_name='URL del Botón')),
                ('imagen_fondo', models.ImageField(upload_to='hero/backgrounds/', verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': '1. Configuración de la Sección Hero',
                'verbose_name_plural': '1. Configuración de la Sección Hero',
            },
        ),
        migrations.CreateModel(
            name='HomePageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloque', models.CharField(choices=[('reflexion', 'Reflexión (Texto simple con título)'), ('texto_fondo', 'Texto con Imagen de Fondo (Estática)'), ('parallax', 'Sección con Efecto Parallax'), ('seccion_valoradas', 'Sección: Lecturas Mejor Valoradas'), ('seccion_recientes', 'Sección: Novedades'), ('seccion_foros', 'Sección: Foros Más Activos')], default='reflexion', help_text='Elige el diseño visual para este bloque de contenido.', max_length=30, verbose_name='Tipo de Bloque')),
                ('titulo', models.CharField(blank=True, help_text='El título principal del bloque.', max_length=200)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="El cuerpo principal del bloque. No es necesario para los bloques de 'Sección'.", verbose_name='Contenido')),
                ('imagen_fondo', models.ImageField(blank=True, help_text="Sube una imagen de fondo (solo para el tipo 'Texto con Imagen de Fondo').", null=True, upload_to='home_blocks/backgrounds/', verbose_name='Imagen de Fondo')),
                ('posicion_contenido', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', help_text='Elige dónde aparecerá el texto.', max_length=10, verbose_name='Posición del Contenido')),
                ('enlace_texto_1', models.CharField(blank=True, max_length=50, verbose_name='Texto del Botón 1')),
                ('enlace_url_1', models.CharField(blank=True, max_length=255, verbose_name='URL del Botón 1')),
                ('enlace_estilo_1', models.CharField(choices=[('primary', 'Primario (Relleno)'), ('secondary', 'Secundario (Borde)')], default='primary', max_length=10, verbose_name='Estilo del Botón 1')),
                ('enlace_nueva_pestana_1', models.BooleanField(default=False, verbose_name='¿Abrir en pestaña nueva?')),
                ('enlace_texto_2', models.CharField(blank=True, max_length=50, verbose_name='Texto del Botón 2')),
                ('enlace_url_2', models.CharField(blank=True, max_length=255, verbose_name='URL del Botón 2')),
                ('enlace_estilo_2', models.CharField(choices=[('primary', 'Primario (Relleno)'), ('secondary', 'Secundario (Borde)')], default='secondary', max_length=10, verbose_name='Estilo del Botón 2')),
                ('enlace_nueva_pestana_2', models.BooleanField(default=False, verbose_name='¿Abrir en pestaña nueva?')),
                ('activo', models.BooleanField(default=True, help_text='Desmarca esta casilla para ocultar el bloque de la página de inicio sin borrarlo.', verbose_name='Bloque Activo')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': '2. Bloque de la Página de Inicio',
                'verbose_name_plural': '2. Bloques de la Página de Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
